## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Markus Traber"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = ""
  logo = "images/banner.jpg"
  favicon = false

[Params.social]
  github = "https://github.com/markusTraber"
  email = "hi@markustraber.com"
  instagram = "https://www.instagram.com/markus_traber/"
  linkedin = "https://www.linkedin.com/in/markus-traber-349981193"

##  telegram = "https://telegram.org"
##  twitter = "https://twitter.com/caressofsteel_"